version: "3"
services:
  backend:
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
